# Site settings
author: Betelhem Elfagid
title: 
header-img: img/home-bg.png
email: betty_elfagid@yahoo.co.uk
copyright_name: Betelhem Elfagid
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  B-Elfagid

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
